project:
  type: manuscript
  execute-dir: project

manuscript:
  article: index.qmd

number-sections: true

date: last-modified
date-format: full

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

execute:
  freeze: auto

bibliography: references.bib

csl: drug-safety.csl