project:
  type: manuscript
  execute-dir: project
  render:
    - notebooks/01-data-cleaning.qmd
    - notebooks/03A-expert-survey-processing.qmd
    - notebooks/02-descriptive-statistics.qmd
    - notebooks/03-apparent-performance.qmd
    - notebooks/04-internal-external-cross-performance.qmd
    - notebooks/05-risk-score.qmd
    # - notebooks/06-model-fairness.qmd
    - index.qmd

manuscript:
  article: index.qmd
  code-links: repo

number-sections: false

date: last-modified
date-format: full

format:
  html:
    comments:
      hypothesis: true
    theme:
      light: flatly
      dark: darkly
  docx: default
  pdf: default

bibliography: references.bib

csl: drug-safety.csl