---
title: Development and Validation of a Risk Prediction Model of linezolid-induced thrombocytopenia in Vietnamese patients

# authors:
#   - name: Norah Jones
#     affiliation: The University
#     roles: writing
#     corresponding: true
# bibliography: references.bib

css: styles.css
---

## Objectives
1. Investigating risk factors of linezolid-induced thrombocytopenia (LI-TP)
2. Developing and validating a logistics regression model to predict LI-TP in Vietnamese patients

## Data cleaning

```{r}
source("notebooks/initialize-data-analysis.r")
```

:::{.scrolling}

```{r}
data_patient_complete |> select(all_of(predictor_list), flag_ADR_TP_ID, site) |> glimpse()
```

:::

## Descriptive statistics

```{r}
load("data/results/table-descriptive.rda")
```

:::{.scrolling}

```{r}
table_descriptive
```

:::

## Model Performance

```{r}
load("data/model-performance/apparent-performance-metrics.rda")
load("data/model-performance/corrected-performance-metrics.rda")
load("data/model-performance/fold-performance-metrics.rda")
load("data/model-performance/cross-performance-metrics.rda")

data_list <- list(
  apparent_performance_metrics,
  corrected_performance_metrics,
  fold_performance_metrics
)
performance_type_list <- c("Apparent", "Bootstrap", "Fold")
initial_string_list <- c("apparent_", "corrected_", "mean_fold_")

reformat_performance_metrics <- function(data, type, string) {
  data |> 
    mutate(
    performance_type = type
  ) |>
  rename_with(~ str_replace(., string, "")) |>
  select(performance_type, everything())
}

performance_metrics <- pmap(
  list(data_list, performance_type_list, initial_string_list), 
  reformat_performance_metrics
) |> bind_rows()

performance_metrics |> knitr::kable()
```