---
title: Expert Opinion Survey processing
---

# Spaghetti code warning
```{r}
library(tidyverse)
library(ggstats)
library(gtsummary)
```

```{r}
data_survey <- read_csv("data/data-original-processed/survey_results.csv") |>
  select(-comorb_hematological)
```

```{r}
data_survey_factor <- data_survey |>
  mutate(across(everything(), ~ factor(.x, levels = c(1:5))))
```

```{r}
gglikert(data_survey_factor, sort = "descending", sort_method = "mean")
gglikert_stacked(data_survey_factor, sort = "descending", sort_method = "mean", add_median_line = TRUE)
```

```{r}
table_survey_summary <- data_survey |>
  tbl_summary(type = ~"continuous", statistic = list(all_continuous() ~ "{mean} | {median} ({p25} - {p75})"))

survey_summary <- data_survey |>
  summarise(across(everything(), list(median = median, IQR = IQR, mean = mean, sd = sd), .names = "{.fn}.{.col}")) |>
  pivot_longer(
    cols = everything(),
    names_to = c(".value", "variable"),
    names_pattern = "(mean|median|IQR|sd)\\.(.*)"
  )

variables_consensus <- survey_summary |>
  filter((median >= 4 & IQR <= 1) | (mean >= 3.5 & sd <= 1)) |>
  arrange(desc(median), desc(mean)) |>
  pull(variable)

data_survey_factor |>
  select(all_of(variables_consensus)) |>
  gglikert(sort = "descending", sort_method = "mean")
```

```{r}
data_patient_screen_full <- data_patient_transformed |>
  mutate(
    across(where(is.logical), as.factor)
  )

# Assuming `data_patient_screen_full` is your data frame
single_level_factors <- data_patient_screen_full |>
  purrr::map_lgl(~ is.factor(.x) && length(levels(.x)) == 1)

# Print the names of the variables that are factors with only one level
variables_to_remove <- names(single_level_factors)[single_level_factors]
```

```{r}
variables_to_screen_short <- variables_consensus

variables_to_screen_short[str_detect(variables_to_screen_short, "\\d")] <- str_remove(variables_to_screen_short[str_detect(variables_to_screen_short, "_\\d+")], "_\\d+")

variables_to_screen_short[str_detect(variables_to_screen_short, "LZD_duration")] <- "LZD_duration_14"

variables_to_screen_short <- unique(variables_to_screen_short)
```

```{r}
variables_to_screen_short_binary <- variables_consensus

variables_to_screen_short_binary[str_detect(variables_to_screen_short_binary, "\\d")] <- str_remove(variables_to_screen_short_binary[str_detect(variables_to_screen_short_binary, "_\\d+")], "_\\d+")

variables_to_screen_short_binary[str_detect(variables_to_screen_short_binary, "LZD_duration")] <- "LZD_duration_14"

variables_to_screen_short_binary[str_detect(variables_to_screen_short_binary, "baseline_CLCR")] <- "baseline_CLCR_30"

variables_to_screen_short_binary <- unique(variables_to_screen_short_binary)
```

```{r}
variables_to_screen_binary <- survey_summary |>
  arrange(desc(median), desc(mean)) |>
  pull(variable)

variables_to_screen_binary[str_detect(variables_to_screen_binary, "\\d")] <- str_remove(variables_to_screen_binary[str_detect(variables_to_screen_binary, "_\\d+")], "_\\d+")

variables_to_screen_binary[str_detect(variables_to_screen_binary, "LZD_duration")] <- "LZD_duration_14"

variables_to_screen_binary[str_detect(variables_to_screen_binary, "baseline_CLCR")] <- "baseline_CLCR_30"

variables_to_screen_binary <- unique(variables_to_screen_binary)

variables_to_screen_binary <- variables_to_screen_binary[1:21]
```

```{r}
variables_to_screen <- survey_summary |>
  arrange(desc(median), desc(mean)) |>
  pull(variable)

variables_to_screen[str_detect(variables_to_screen, "\\d")] <- str_remove(variables_to_screen[str_detect(variables_to_screen, "_\\d+")], "_\\d+")

variables_to_screen[str_detect(variables_to_screen, "LZD_duration")] <- "LZD_duration_14"

variables_to_screen <- unique(variables_to_screen)

variables_to_screen <- variables_to_screen[1:21]

variables_to_force <- variables_to_screen[1:5]

variables_to_force_top_3 <- variables_to_screen[1:3]

variables_out <- survey_summary |>
  filter(!variable %in% variables_to_screen)
```

```{r}
variables_to_force_binary <- survey_summary |>
  arrange(desc(median), desc(mean)) |>
  pull(variable) |>
  head(5)
```

```{r}
variables_to_screen_all <- survey_summary |>
  arrange(desc(median), desc(mean)) |>
  pull(variable)

variables_to_screen_all[str_detect(variables_to_screen_all, "\\d")] <- str_remove(variables_to_screen_all[str_detect(variables_to_screen_all, "_\\d+")], "_\\d+")

variables_to_screen_all[str_detect(variables_to_screen_all, "LZD_duration")] <- "LZD_duration_14"

variables_to_screen_all[str_detect(variables_to_screen_all, "LZD_route")] <- "LZD_route_IV"

variables_to_screen_all <- unique(variables_to_screen_all) |> setdiff(variables_to_remove)
```

```{r}
variables_to_screen_all_binary <- survey_summary |>
  arrange(desc(median), desc(mean)) |>
  pull(variable)

variables_to_screen_all_binary[str_detect(variables_to_screen_all_binary, "\\d")] <- str_remove(variables_to_screen_all_binary[str_detect(variables_to_screen_all_binary, "_\\d+")], "_\\d+")

variables_to_screen_all_binary[str_detect(variables_to_screen_all_binary, "LZD_duration")] <- "LZD_duration_14"

variables_to_screen_all_binary[str_detect(variables_to_screen_all_binary, "baseline_CLCR")] <- "baseline_CLCR_30"

variables_to_screen_all_binary[str_detect(variables_to_screen_all_binary, "LZD_route")] <- "LZD_route_IV"

variables_to_screen_all_binary <- unique(variables_to_screen_all_binary) |> setdiff(variables_to_remove)
```

```{r}
save(variables_to_screen, file = "data/results/variables-to-screen.rda")
save(variables_to_screen_short, file = "data/results/variables-to-screen-short.rda")
save(variables_to_screen_short_binary, file = "data/results/variables-to-screen-short-binary.rda")
save(variables_to_screen_binary, file = "data/results/variables-to-screen-binary.rda")
save(variables_to_screen_all, file = "data/results/variables-to-screen-all.rda")
save(variables_to_screen_all_binary, file = "data/results/variables-to-screen-all-binary.rda")

save(variables_to_force, file = "data/results/variables-to-force.rda")
save(variables_to_force_binary, file = "data/results/variables-to-force-binary.rda")
save(variables_to_force_top_3, file = "data/results/variables-to-force-top-3.rda")
```