---
title: Descriptive Statistics
---

```{r}
library(tidyverse)

data_complete <- read_csv("data/data-cleaned/data-complete.csv")
data_patient_complete <- read_csv("data/data-cleaned/data-patient-complete.csv")
```

```{r}
predictor_list <- data_patient_complete |>
  select(
    patient_age, patient_sex, LZD_dose_per_weight, baseline_CLCR, dept_ER, dept_ICU, baseline_HGB, baseline_WBC, baseline_PLT, LZD_duration, starts_with("invasive"), starts_with("comorb"), starts_with("infect"), comed_aspirin, comed_diclofenac, comed_ibuprofen, comed_paracetamol, comed_penicillin, comed_cepha, comed_carbapenem, comed_cotrimoxazol, comed_vancomycin, comed_levofloxacin, comed_teicoplanin, comed_ethambutol, comed_pyrazinamid, comed_rifampin, comed_heparin, comed_clopidogrel, comed_enoxaparin, comed_dexamethason, comed_amiodaron, comed_furosemid, comed_haloperidol, comed_valproic
  ) |>
  colnames()
```

```{r}
library(gtsummary)

table_stats <- data_patient_complete |>
  select(
    all_of(predictor_list), starts_with("comed"), flag_ADR_TP_ID
  ) |>
  tbl_summary(
    by = flag_ADR_TP_ID,
    statistic = list(all_continuous() ~ "{median} ({p25} - {p75})"),
    missing = "no"
  ) |>
  modify_table_body(
    ~ .x |>
      mutate(stat_1 = if_else(str_detect(stat_1, "NA"), NA, stat_1))
  ) |>
  add_overall() |>
  bold_labels()
```

```{r}
library(tidymodels)
library(furrr)

data_patient_complete_response_as_factor <- data_patient_complete |>
  mutate(
    flag_ADR_TP_ID = as.factor(flag_ADR_TP_ID)
  )

fit_univariate_regression <- function(predictor) {
  model <- logistic_reg() |>
    set_engine("glm") |>
    set_mode("classification") |>
    fit(
      reformulate(
        termlabels = predictor,
        response = "flag_ADR_TP_ID"
      ),
      data = data_patient_complete_response_as_factor
    )
}

arrange_univariate_regression <- function(model) {
  model |>
    tbl_regression(
      exponentiate = TRUE,
      show_single_row = everything()
    ) |>
    bold_p()
}

plan(multisession, workers = parallel::detectCores() - 2)
uni_model_list <- future_map(predictor_list, fit_univariate_regression)
table_uni_list <- future_map(uni_model_list, arrange_univariate_regression)
plan(sequential)

table_uni <- tbl_stack(table_uni_list)
```

```{r}
table_descriptive <- tbl_merge(list(table_stats, table_uni))
table_descriptive
```